### PR TITLE
Update ramda dependency

### PR DESCRIPTION
**Pull request by crash7**
I need to solve a couple of security issues that older ramda versions have. Check all the usage and it's safe to update to latest.

### CODE REVIEW

**Comment by icavina** [comment]
@adepretis @fhelmberger @busypeoples @AutoSponge sorry for the inconvenience, not sure if you are still maintaining this repo, but it would be really nice if this can be merged. Thanks a lot in advance!

**Comment by adepretis** [comment]
Just merged it. Unfortunately this project is no longer maintained @crash7 :-(

@busypeoples do you want to officially take over the repository? Otherwise would you be interested @crash7?

**Comment by icavina** [comment]
Thanks @adepretis! Do you know if a new release will be triggered?

**Comment by adepretis** [comment]
@icavina uh, good point. As far as I remember we never had a pipeline in place and the package was published without organizational scope - so I guess @busypeoples has been maintaining this on npm. Can you publish it once again/once more?

**Comment by crash7** [comment]
@adepretis thanks for merging this!

Happy to help with future PRs reviews or security updates!

**Comment by crash7** [comment]
@adepretis I can also handle the npm publish if you want or if @busypeoples is not available.

**Comment by adepretis** [comment]
I don't have the credentials @crash7 ... trying to get a hold of @busypeoples currently, I'll get back to you ASAP

**Comment by busypeoples** [comment]
@crash7 Thanks for the PR! Will publish an update. Thanks for merging @adepretis.

**Comment by busypeoples** [comment]
Ok, published `v.0.7.2` @crash7 @icavina @adepretis

**Comment by crash7** [comment]
Thank you @busypeoples!

**Pull request merged**
