### PR TITLE
Add support for arrays of non-object values

### PR DESCRIPTION
**Pull request by jakubkoci**
I have just been playing around possible solution of #85 for myself and this is the result. Maybe, it helps you somehow. I am just sharing more about my idea.

### CODE REVIEW

**Comment by busypeoples** [comment]
@jakubkoci Thanks! I'll have a look later today and give you feedback!

**Comment by busypeoples** [comment]
Check #87 
We should enable to validate against any array input. How the input is validated is up to the user. 
We don't care if the input is `['a', 'b']` or `[{id:1}, {id: 3}]`, the corresponding predicate function has to know how to validate the input.

**Comment by busypeoples** [comment]
I will close this PR now, as #87 has been merged and resolves #85. Thanks for your very valuable input!

**Comment by jakubkoci** [comment]
Yes. I agree it's way more better solution, even simpler. Thanks for quick update.

**Pull request closed without merging**
